---
# Source: orderservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-orderservice
  labels:
    helm.sh/chart: orderservice-0.1.0
    app.kubernetes.io/name: orderservice
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: orderservice
    app.kubernetes.io/instance: release-name
---
# Source: orderservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-orderservice
  labels:
    helm.sh/chart: orderservice-0.1.0
    app.kubernetes.io/name: orderservice
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orderservice
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: orderservice-0.1.0
        app.kubernetes.io/name: orderservice
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      containers:
        - name: orderservice
          image: "orderservice:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
---
# Source: orderservice/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-orderservice-test-connection"
  labels:
    helm.sh/chart: orderservice-0.1.0
    app.kubernetes.io/name: orderservice
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-orderservice:8081']
  restartPolicy: Never
